# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('pic', models.FileField(default='', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('pages', models.PositiveIntegerField(default=500)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=3.6)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2017, 7, 4, 10, 54, 19, 182839, tzinfo=utc))),
                ('cover', models.FileField(default='', upload_to=b'')),
                ('author', models.ManyToManyField(to='second.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('num_awards', models.IntegerField()),
                ('pic', models.FileField(default='', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('registered_users', models.PositiveIntegerField()),
                ('pic', models.FileField(default='', upload_to=b'')),
                ('books', models.ManyToManyField(to='second.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Publisher'),
        ),
    ]
