# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_auto_20170704_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 11, 7, 58, 910927, tzinfo=utc)),
        ),
    ]
