# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_auto_20170705_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 6, 4, 43, 147452, tzinfo=utc)),
        ),
    ]
