# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_auto_20170705_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fantcy', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 5, 11, 58, 24, 694963, tzinfo=utc)),
        ),
    ]
