# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_auto_20170706_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 5, 16, 25, 784315, tzinfo=utc)),
        ),
    ]
