# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_auto_20170710_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Book'),
        ),
    ]
