# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0011_auto_20170710_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
