# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0012_auto_20170710_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
    ]
