# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0013_auto_20170712_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='book_file',
        ),
    ]
